### ISSUE TITLE
Download file giving a 502 error

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/OCWA#79]
# OCWA Issue

## User Story

**As a** _< researcher >_,<br>
**I want** _< to download the files that I have requested from the SRE for export >_<br>
**so that** _< I can do as I wish with them >_.

### ENV

`STG`

### TESTCASE

- Upload a file that has no file type extension
- Go through the approval
- From the download application, select the file for download

### EXPECTED

- File is downloaded

### ACTUAL

- 502 error

### ERROR

```
_http_outgoing.js:464
    throw err;
    ^

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at ServerResponse.setWriteHeadHeaders (/usr/src/app/node_modules/on-headers/index.js:82:19)
    at ServerResponse.writeHead (/usr/src/app/node_modules/on-headers/index.js:41:36)
    at IncomingMessage.stream.on (/usr/src/app/server/routes/files.js:53:9)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Jonesy** [comment]
Tried this on dev with a LICENSE file, and it downloaded, I think this is closed.

**Comment by ikethecoder** [comment]
I verified this in staging and confirmed it is fixed as well.
